[package]
edition = "2018"
build = "build.rs"
name = "game-scanner"
description = "Game Scanner for any launcher and OS"
version = "1.0.1"
authors = ["Matheus Albino <matheusalbino@users.noreply.github.com>"]
license = "MIT"
keywords = ["games", "api-bindings"]
homepage = "https://github.com/EqualGames/game-scanner"
repository = "https://github.com/EqualGames/game-scanner"
readme = "README.md"
include = [
    "src/**/*.proto",
    "src/**/*.rs",
    "build.rs",
    "Cargo.toml",
]

[lib]
name = "game_scanner"
bench = true
doc = true
crate-type = ["rlib", "cdylib"]

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = { version = "1.0.64" }
serde_yaml = { version = "0.8.17" }
url = { version = "2.2.2" }
rusqlite = { version = "0.25.3", features = ["bundled"] }
sysinfo = { version = "0.17.5" }
prost = { version = "0.7.0" }
prost-types = { version = "0.7.0" }
bytes = { version = "1.0.1" }
chrono = { version = "0.4.19" }

[target.'cfg(target_os = "windows")'.dependencies]
case = { version = "1.0.0" }
directories = { version = "3.0.2" }
winreg = { version = "0.8.0" }

[dev-dependencies]
criterion = { version = "0.3.4" }

[build-dependencies]
prost-build = { version = "0.7.0" }
