[package]
name = "game-scan"
version = "0.1.0"
authors = ["Matheus Albino <matheusalbino@users.noreply.github.com>"]
edition = "2018"
publish = false

[lib]
name = "libgamescan"
crate-type = ["rlib", "cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] } # MIT/Apache License
serde_json = "1.0" # MIT/Apache License
case = "1.0.0"  # MIT License
url = "2.2.0"  # MIT/Apache License
rusqlite = { version = "0.24.2", features = ["bundled"] } # MIT License
directories = "3.0.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.8.0" # MIT License