on:
  pull_request:
    branches:
      - main
      - develop

name: Test

jobs:

  cargo_test:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --package game-scanner

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package game-scanner

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package game-scanner --lib --release

  node_test:
    needs: cargo_test
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - run: |
          cd node
          npm ci

      - run: |
          cd node
          npm run build